# Generated by Django 5.0.2 on 2024-07-19 19:45

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdef12345', length=5, max_length=10, prefix='', unique=True)),
                ('titulo', models.CharField(help_text='Categoria do Produto', max_length=50)),
                ('imagem', models.ImageField(upload_to='categoria')),
            ],
            options={
                'verbose_name_plural': 'categorias',
            },
        ),
    ]
